### ISSUE TITLE
getting error from another account spoke vpc

### ISSUE THREAD

**Issue by rajeevsh7** [fortinetsolutions/AWS-CloudFormationTemplates#1]
An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError
Traceback (most recent call last):
File "/var/task/spokevgw_function.py", line 31, in spokevgw_handler
s3.Object(TransitS3Bucket, 'transitvpc.txt').load()
File "/var/task/boto3/resources/factory.py", line 505, in do_action
response = action(self, *args, **kwargs)
File "/var/task/boto3/resources/action.py", line 83, in __call__
response = getattr(parent.meta.client, operation_name)(**params)
File "/var/task/botocore/client.py", line 253, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/task/botocore/client.py", line 544, in _make_api_call
raise error_class(parsed_response, operation_name)
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by dlonraekim** [comment]
Has anyone been able to resolve this error?

**Comment by dlonraekim** [comment]
I was able to run this template without producing the 403 error, and was able to successfully create cross-account tunnels from VPC to Fortigate c5.xlarge v5.6.4

AWS-CloudFormationTemplates/Templates/deprecated/TransitVPC-FortiGate_Spoke_SecondAccount.json
